version: '3.6'
services:
  registry:
    image: 'registry:2'
    ports:
      - 5000:5000
    environment: 
      REGISTRY_HTTP_ADDR: '0.0.0.0:5000'
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
    volumes:
      - '/data/registry:/var/lib/registry'